### ISSUE TITLE
Fix the position of Footer component

### ISSUE THREAD

**Issue by Chihori-Suzuki** [YumiMachino/recipe-book#29]
Heroコンポーネント Position: absolute にするとなぜかFooterが下に固定されない問題

![Screen Shot 2021-12-15 at 18 43 43](https://user-images.githubusercontent.com/69213233/146298456-6880d94a-175e-40f6-8bff-f7dea954e171.png)

**Comment by YumiMachino** [comment]
Layout componentの高さをmin height100vhで設定してるから、childrenの高さをちゃんと設定しないとfooterがcollapseして下部に表示されなくなるのが関係しているかも

**Comment by YumiMachino** [comment]
今mainとマージしてみて確認してみたけど、Footer ちゃんと下になってるけどFixできた感じ？？

**Comment by Chihori-Suzuki** [comment]
なんかmain のブランチで見ると固定されてるけど、私のブランチで見ると固定できていない、、😂

**Comment by YumiMachino** [comment]
ちおりのブランチの Layout component確認したけど、最新のになってないっぽい。
(結構前だけどスタイリングを追加したんだよね)
mainとマージしたら解決するかも。

**Comment by Chihori-Suzuki** [comment]
なるなる！そしたらpullしとく！ありがとう！
